// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuhOf22onwTPiV3kLb37Uwx0ThnjNs8uU',
    appId: '1:595744277476:web:c961658086608f49443df1',
    messagingSenderId: '595744277476',
    projectId: 'tippytoes-app',
    authDomain: 'tippytoes-app.firebaseapp.com',
    storageBucket: 'tippytoes-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWqMfLfF-N1SFM8oimneFjmTgAupFK4R0',
    appId: '1:595744277476:android:ccd13c83c15bea95443df1',
    messagingSenderId: '595744277476',
    projectId: 'tippytoes-app',
    storageBucket: 'tippytoes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ydJdfuCCnXihdv_KneT0tOrp06A6C6Y',
    appId: '1:595744277476:ios:2f05658543b93369443df1',
    messagingSenderId: '595744277476',
    projectId: 'tippytoes-app',
    storageBucket: 'tippytoes-app.appspot.com',
    iosClientId: '595744277476-dj9rg5cuaquft4k7ndb9vikdiic17ch1.apps.googleusercontent.com',
    iosBundleId: 'us.tippytoes.tippytoesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ydJdfuCCnXihdv_KneT0tOrp06A6C6Y',
    appId: '1:595744277476:ios:2f05658543b93369443df1',
    messagingSenderId: '595744277476',
    projectId: 'tippytoes-app',
    storageBucket: 'tippytoes-app.appspot.com',
    iosClientId: '595744277476-dj9rg5cuaquft4k7ndb9vikdiic17ch1.apps.googleusercontent.com',
    iosBundleId: 'us.tippytoes.tippytoesapp',
  );
}
